export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_PROFILE_REQUEST = 'PRODUCT_PROFILE_REQUEST';
export const PRODUCT_PROFILE_SUCCESS = 'PRODUCT_PROFILE_SUCCESS';
export const PRODUCT_PROFILE_FAIL = 'PRODUCT_PROFILE_FAIL';

export const TROLLEY_ADD_ITEM = 'TROLLEY_ADD_ITEM';
export const TROLLEY_REMOVE_ITEM = 'TROLLEY_REMOVE_ITEM';
export const TROLLEY_SAVE_DELIVERY_ADDRESS = 'TROLLEY_SAVE_DELIVERY_ADDRESS';
export const TROLLEY_SAVE_PAYMENT_METHOD = 'TROLLEY_SAVE_PAYMENT_METHOD';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
